/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: MIT
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/MIT
 */

import { setRenderer } from '@lwc/engine-core';

import {
    assertInstanceOfHTMLElement,
    attachShadow,
    createComment,
    createElement,
    createText,
    defineCustomElement,
    dispatchEvent,
    getAttribute,
    getBoundingClientRect,
    getChildNodes,
    getChildren,
    getClassList,
    getCustomElement,
    getElementsByClassName,
    getElementsByTagName,
    getFirstChild,
    getFirstElementChild,
    getLastChild,
    getLastElementChild,
    getProperty,
    HTMLElement,
    insert,
    insertGlobalStylesheet,
    insertStylesheet,
    isConnected,
    isHydrating,
    isNativeShadowDefined,
    isSyntheticShadowDefined,
    nextSibling,
    querySelector,
    querySelectorAll,
    remove,
    removeAttribute,
    removeEventListener,
    setAttribute,
    setCSSStyleProperty,
    setProperty,
    setText,
    ssr,
    addEventListener,
} from './renderer';

setRenderer({
    assertInstanceOfHTMLElement,
    attachShadow,
    createComment,
    createElement,
    createText,
    defineCustomElement,
    dispatchEvent,
    getAttribute,
    getBoundingClientRect,
    getChildNodes,
    getChildren,
    getClassList,
    getCustomElement,
    getElementsByClassName,
    getElementsByTagName,
    getFirstChild,
    getFirstElementChild,
    getLastChild,
    getLastElementChild,
    getProperty,
    HTMLElement,
    insert,
    insertGlobalStylesheet,
    insertStylesheet,
    isConnected,
    isHydrating,
    isNativeShadowDefined,
    isSyntheticShadowDefined,
    nextSibling,
    querySelector,
    querySelectorAll,
    remove,
    removeAttribute,
    removeEventListener,
    setAttribute,
    setCSSStyleProperty,
    setProperty,
    setText,
    ssr,
    addEventListener,
});
